/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src_components.global;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class Glob_ContainerRowContents extends Utils {

    public String Glob_ContainerRowContents(String units, String ComponentsToCall) {
        return "import Title from './Title'\n"
                + "import React from 'react'\n"
                + "import Loader from './Loader'\n"
                + "import { EditTitle } from './Title'\n"
                + "\n"
                + "\n"
                + "// Icons\n"
                + "import { Icon } from 'react-icons-kit'\n"
                + "import { printer } from 'react-icons-kit/icomoon/printer'\n"
                + "import { floppyDisk as save } from 'react-icons-kit/icomoon/floppyDisk'\n"
                + "import { cancelCircle as cancel } from 'react-icons-kit/icomoon/cancelCircle'\n"
                + "import { plus as add } from 'react-icons-kit/icomoon/plus'\n"
                + "import { search } from 'react-icons-kit/icomoon/search'\n"
                + "import { pencil as edit } from 'react-icons-kit/icomoon/pencil'\n"
                + "import { cross as remove } from 'react-icons-kit/icomoon/cross'\n"
                + "import { forward as point } from 'react-icons-kit/icomoon/forward'\n"
                + "import { arrowRight as Mainpoint } from 'react-icons-kit/icomoon/arrowRight'\n"
                + "\n"
                + "import { calendar } from 'react-icons-kit/icomoon/calendar'\n"
                + "import { Link } from 'react-router-dom'\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "export default function ContainerRow(props) {\n"
                + "    return (\n"
                + "        <div>\n"
                + "            <div className='container'>\n"
                + "                <div className=\"row\">\n"
                + "                    {props.children}\n"
                + "\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "export  function ContainerRowFull(props) {\n"
                + "    return (\n"
                + "        <div>\n"
                + "            <div className='container-fluid'>\n"
                + "                <div className=\"row\">\n"
                + "                    {props.children}\n"
                + "\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "\n"
                + "export const ContainerRowHalf = (props) => {\n"
                + "    return <ContainerRow>\n"
                + "        <div className='col-6  '>\n"
                + "            {props.children}\n"
                + "        </div>\n"
                + "    </ContainerRow>\n"
                + "}\n"
                + "export const SaveUpdateBtns = (props) => {\n"
                + "    return (\n"
                + "        <div className='row'>\n"
                + "            <div className='col-6 d-flex   justify-content-start '>\n"
                + "                {props.clearBtn &&\n"
                + "                    <button type='button' onClick={props.clearHandle} className='mt-4 btn btn-danger'>\n"
                + "                        <Icon style={{ color: '#fff', marginRight: \"10px\" }} icon={cancel} />\n"
                + "                        Cancel</button>\n"
                + "                }\n"
                + "\n"
                + "            </div>\n"
                + "            <div className='col-6   d-flex   justify-content-start'>\n"
                + "                <button type=\"submit\" className=\"mt-4 btn   offset-6 col-6  \" style={{ fontSize: \"12px\", backgroundColor: \"#470343\", color: \"#fff\", fontWeight: \"bolder\" }} >\n"
                + "                    <Icon style={{ color: '#fff', marginRight: \"10px\" }} icon={save} />\n"
                + "                    {props.saveOrUpdate}</button>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "export const SaveUpdateBtnsBtnNear = (props) => {\n"
                + "    return (\n"
                + "        <div className='col-6   d-flex   justify-content-start'>\n"
                + "            <button type=\"submit\"  className=\"mt-2 btn   offset-6 col-6  \" style={{ fontSize: \"12px\", backgroundColor: \"#470343\", color: \"#fff\", fontWeight: \"bolder\" }} >\n"
                + "                <Icon style={{ color: '#fff', marginRight: \"10px\" }} icon={save} />\n"
                + "                {props.saveOrUpdate}</button>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export const ContainerForm = (props) => {\n"
                + "    return (\n"
                + "        <div className=\"container\">\n"
                + "            <div className='form-row'>\n"
                + "                {props.children}\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "export const FormInnerRightPane = (props) => {\n"
                + "    return (\n"
                + "        <div className={`box col-lg-8 col-md-8 ms-3   formBox p-3 mt-${props.mt}`}  >\n"
                + "            <div className='form-row'>\n"
                + "                <form onSubmit={props.onSubmitHandler} id=\"Form\">\n"
                + "                    {props.children}\n"
                + "                </form>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export const ContainerRowBtwn = (props) => { /*Thsi is on the form fields*/\n"
                + "    return (\n"
                + "        <>\n"
                + "            <div className=\"container\" classname=\"formPane\">\n"
                + "                <div className='row  d-flex justify-content-between align-top'>\n"
                + "                    {props.clearBtn && <EditTitle name={props.form} />}\n"
                + "                    {!props.clearBtn && <Title name={props.form} />}\n"
                + "                    {props.children}\n"
                + "\n"
                + "\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </>\n"
                + "    )\n"
                + "}\n"
                + "export const FormSidePane = () => {\n"
                + "    return (\n"
                + "        <div className='col-lg-3 d-flex align-start align-items-start   fs-1  rounded-circle col-md-3  totalBox  g-light'>\n"
                + "            <ul className='totalBoxList '>\n"
                + "                <li>\n"
                + "                    <h6><Icon icon={Mainpoint} />   DataItem 1</h6>\n"
                + "                    <p><Icon size={12} style={{ marginLeft: \"20px\", marginRight: \"6px\" }} icon={point} />\n"
                + "                        45 &nbsp;&nbsp;    <Link className='text-white' to=\"#\"> <Icon size={12} icon={calendar} />    {new Date().getFullYear()} </Link> </p>\n"
                + "                </li>\n"
                + "                <li><h6><Icon icon={Mainpoint} />  Data item 2 </h6>\n"
                + "                    <p><Icon style={{ marginLeft: \"20px\", marginRight: \"6px\" }} icon={point} />\n"
                + "                        23 &nbsp;&nbsp;\n"
                + "                        <Link className='text-white' to=\"#\"> <Icon size={12} icon={calendar} /> {new Date().getFullYear()} </Link>\n"
                + "                    </p>\n"
                + "                </li>\n"
                + "            </ul>\n"
                + "        </div>)\n"
                + "}\n"
                + "\n"
                + "export const ClearBtnSaveStatus = (props) => {\n"
                + "    return (<div className='box col-lg-8 col-md-8  ms-3  ' >\n"
                + "        {props.showLoader && <Loader />}\n"
                + "        {props.showAlert && (props.height == 0) &&\n"
                + "            <div class=\"alert alert-primary\" role=\"alert\">\n"
                + "                Record Saved Successfully!\n"
                + "            </div>\n"
                + "        }\n"
                + "\n"
                + "    </div>\n"
                + "    )\n"
                + "}";
    }
}
