/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src_components.global;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class Glob_Footer extends Utils {

    public String AppCss(String units, String ComponentsToCall) {
        return "import React from 'react'\n"
                + "import Icon from 'react-icons-kit'\n"
                + "\n"
                + "import { facebook } from 'react-icons-kit/icomoon/facebook'\n"
                + "import { google } from 'react-icons-kit/icomoon/google'\n"
                + "import { twitter } from 'react-icons-kit/icomoon/twitter'\n"
                + "import { linkedin } from 'react-icons-kit/icomoon/linkedin'\n"
                + "import { github } from 'react-icons-kit/icomoon/github'\n"
                + "\n"
                + "function Footer() {\n"
                + "    return (\n"
                + "        <>\n"
                + "\n"
                + "            <div className=\"mt-5 footer\">\n"
                + "                <footer className=\"text-center text-white\" style={{ backgroundColor: \"#0a252c\" }}>\n"
                + "                    <div className=\"ro\">\n"
                + "                        <section className=\"mt-5\">\n"
                + "                            <div className=\"row text-center  d-flex justify-content-center pt-5\">\n"
                + "                                <div className=\"col-md-2\">\n"
                + "                                    <h6 className=\"text-uppercase font-weight-bold\">\n"
                + "                                        <a href=\"#!\" className=\"\">About us</a>\n"
                + "                                    </h6>\n"
                + "                                </div>\n"
                + "                                <div className=\"col-md-2\">\n"
                + "                                    <h6 className=\"text-uppercase font-weight-bold\">\n"
                + "                                        <a href=\"#!\" className=\"\">Products</a>\n"
                + "                                    </h6>\n"
                + "                                </div>\n"
                + "\n"
                + "                                <div className=\"col-md-2\">\n"
                + "                                    <h6 className=\"text-uppercase font-weight-bold\">\n"
                + "                                        <a href=\"#!\" className=\"\">Awards</a>\n"
                + "                                    </h6>\n"
                + "                                </div>\n"
                + "                                <div className=\"col-md-2\">\n"
                + "                                    <h6 className=\"text-uppercase font-weight-bold\">\n"
                + "                                        <a href=\"#!\" className=\"\">Contact</a>\n"
                + "                                    </h6>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </section>\n"
                + "\n"
                + "\n"
                + "                        <hr className=\"my-5\" />\n"
                + "\n"
                + "\n"
                + "                        <section className=\"mb-5\">\n"
                + "                            <div className=\"row d-flex justify-content-center \" style={{minHeight:\"150px\"}}>\n"
                + "                            <div className='col-lg-2 col-sm-3  '>\n"
                + "                                \n"
                + "                                <div className='footerLogo me-1'>\n"
                + "                                    Logo\n"
                + "                                </div>\n"
                + "                                <p className='footerAddress mt-2'>Email: info@codeguru-pro.com</p>\n"
                + "                                <p className='footerAddress'>Tel:    (250) 784113888</p>\n"
                + "                            </div>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                                <div className=\"col-lg-8 border border-light\">\n"
                + "                                    <p>\n"
                + "                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt\n"
                + "                                        distinctio earum repellat quaerat voluptatibus placeat nam,\n"
                + "                                        commodi optio pariatur est quia magnam eum harum corrupti\n"
                + "                                        dicta, aliquam sequi voluptate quas.\n"
                + "                                    </p>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </section>\n"
                + "\n"
                + "\n"
                + "                        <section className=\"text-center mb-5\">\n"
                + "                            <Icon icon={facebook} className=\"ms-2\" />\n"
                + "                            <Icon icon={twitter} className=\"ms-2\" />\n"
                + "                            <Icon icon={google} className=\"ms-2\" />\n"
                + "                            <Icon icon={linkedin} className=\"ms-2\" />\n"
                + "                            <Icon icon={github} className=\"ms-2\" />\n"
                + " \n"
                + "                        </section>\n"
                + "\n"
                + "                    </div>\n"
                + "\n"
                + "\n"
                + "                    <div\n"
                + "                        className=\"text-center p-3\"\n"
                + "                        style={{ fontSize:\"12px\", fontWeight:\"bolder\", backgroundColor: \"rgba(0, 0, 0, 0.2)\" }}>\n"
                + "                        2017 -  {new Date().getFullYear()} Copyright: -\n"
                + "                        <a  style={{ textDecoration:\"none\"}} className=\"\" href=\"https://mdbootstrap.com/\"> codeguru-pro.com</a>\n"
                + "\n"
                + "                    </div>\n"
                + "\n"
                + "                </footer>\n"
                + "\n"
                + "            </div>\n"
                + "\n"
                + "\n"
                + "        </>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export default Footer";
    }
}
