/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src_components.global.forms;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class Forms_InputRow extends Utils {

    public String Forms_InputRow() {
        return "import React from 'react'\n"
                + "import OtherStyles from '../../Styles/OtherStyles'\n"
                + "\n"
                + "\n"
                + "function InputRow(props) {\n"
                + "    return (\n"
                + "        <>\n"
                + "            <GenIputRow name={props.name} label={props.label}>\n"
                + "                <input type=\"text\" autoComplete='false' required style={OtherStyles.txt()} value={props.val}\n"
                + "                    onChange={props.handle} className=\"form-control\" id={props.label} />\n"
                + "            </GenIputRow>\n"
                + "        </>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export const BtnInputRow = (props) => {\n"
                + "    return (\n"
                + "        <div class=\"form-group row m-1\">\n"
                + "            <button className='btn  col-sm-3 col-form-label' onClick={props.handle} style={{ color: \"#000\", fontWeight: \"bolder\", backgroundColor: \"#b4c7f2da\" }}> {props.name} </button>\n"
                + "            <div class=\"col-sm-9\">\n"
                + "                <span className='p-2 mt-3'>\n"
                + "                    {props.status}\n"
                + "                </span>\n"
                + "\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export const GenIputRow = (props) => {\n"
                + "    return (\n"
                + "        <div class=\"form-group row m-1\">\n"
                + "            <label for={props.label} class=\"col-sm-3 col-form-label\">{props.name}</label>\n"
                + "            <div class=\"col-sm-9\">\n"
                + "                {props.children}\n"
                + "\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "\n"
                + "\n"
                + "export const DropDownInputWithLoader = (props) => {\n"
                + "    return (<>\n"
                + "\n"
                + "        <GenIputRow name={props.name} label={props.label}>\n"
                + "            <select required style={OtherStyles.txt()} onChange={props.handle} className=\"form-select\" id={props.label} >\n"
                + "                <option></option>\n"
                + "\n"
                + "                {props.children}\n"
                + "            </select>\n"
                + "        </GenIputRow>\n"
                + "    </>)\n"
                + "\n"
                + "}\n"
                + "export const DropDownInput = (props) => {\n"
                + "    return (<>\n"
                + "\n"
                + "        <GenIputRow name={props.name} label={props.label}>\n"
                + "            {props.showmoreload &&\n"
                + "                <div className='row'>\n"
                + "                    <div className='unitsLoading' style={{ backgroundColor: '#fff', position: 'relative', overflow: 'hidden', width: '380px', height: '40px' }}>\n"
                + "                    </div>\n"
                + "                </div>}\n"
                + "            <select required style={OtherStyles.txt()} onChange={props.handle} className=\"form-select\" id={props.label} >\n"
                + "                <option></option>\n"
                + "                {props.children}\n"
                + "            </select>\n"
                + "        </GenIputRow>\n"
                + "    </>)\n"
                + "}\n"
                + "\n"
                + "export const LoadSub = (props) => {\n"
                + "    return (\n"
                + "        <>\n"
                + "            {props.showmoreload &&\n"
                + "                <div className='row'>\n"
                + "                    <div className='unitsLoading' style={{ backgroundColor: '#fff', position: 'relative', overflow: 'hidden', width: '380px', height: '40px' }}>\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "            }\n"
                + "        </>\n"
                + "    )\n"
                + "}\n"
                + "export const EmptyInputRow = (props) => {\n"
                + "    return (\n"
                + "        <>\n"
                + "            <GenIputRow name={props.name} label={props.label}>\n"
                + "                <input type=\"text\" autoComplete='false' style={OtherStyles.txt()} value={props.val}\n"
                + "                    onChange={props.handle} className=\"form-control\" id={props.label} />\n"
                + "\n"
                + "            </GenIputRow>\n"
                + "        </>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "\n"
                + "\n"
                + "export default InputRow";
    }
}
