/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src_components.navbar;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class NavBarContents extends Utils {

    public String NavBarContents(String ListMenus) {
        return "import React from 'react'\n"
                + "import { Link } from 'react-router-dom';\n"
                + "import NavLinks from './NavLinks';\n"
                + "\n"
                + "import { Icon } from 'react-icons-kit'\n"
                + "import { man } from 'react-icons-kit/icomoon/man'\n"
                + "import { compass } from 'react-icons-kit/icomoon/compass'\n"
                + "import { pencil2 as arrival } from 'react-icons-kit/icomoon/pencil2'\n"
                + "import { checkmark as tally } from 'react-icons-kit/icomoon/checkmark'\n"
                + "import { coinDollar as invoice } from 'react-icons-kit/icomoon/coinDollar'\n"
                + "import { stack as receipt } from 'react-icons-kit/icomoon/stack'\n"
                + "import { printer } from 'react-icons-kit/icomoon/printer'\n"
                + "import { stack as deploy } from 'react-icons-kit/icomoon/stack'\n"
                + "import { ic_view_week_outline as struc } from 'react-icons-kit/md/ic_view_week_outline'\n"
                + "import {ic_credit_card as layout} from 'react-icons-kit/md/ic_credit_card'\n"
                + "import {ic_next_plan_twotone as more} from 'react-icons-kit/md/ic_next_plan_twotone'\n"
                + "\n"
                + "import Container from 'react-bootstrap/Container';\n"
                + "import Nav from 'react-bootstrap/Nav';\n"
                + "import Navbar from 'react-bootstrap/Navbar';\n"
                + "import NavDropdown from 'react-bootstrap/NavDropdown';\n"
                + "\n"
                + "\n"
                + "export function LocalLoginLink(props) {\n"
                + "    return (\n"
                + "        <li className=\"nav-item\">\n"
                + "            <Link className=\"nav-link  \" style={{ fontSize: \"13px\", fontWeight: \"bold\", color: \"#fff\", marginLeft: \"40px\" }} to={`/${props.path} `}>\n"
                + "                <span style={{ textTransform: 'capitalize' }}>  {`${props.path} `} </span>\n"
                + "            </Link>\n"
                + "        </li>\n"
                + "    )\n"
                + "}\n"
                + "function NavbarBar() {\n"
                + "    let my_class = \"background-color: #2ccdf5;  \";\n"
                + "    const navLinks = {\n"
                + "        color: \"#fff\",\n"
                + "        textDecoration: \"none\",\n"
                + "        fontWeight: \"bolder\",\n"
                + "        fontFamily: \"arial black\",\n"
                + "        fontSize: \"13px\",\n"
                + "        textShadow: \"0px 0px 5px #000\",\n"
                + "        marginLeft: \"12px\"\n"
                + "    };\n"
                + "    const nav_styles = {\n"
                + "        \n"
                + "        backgroundColor: \"rgb(6, 63, 80)\",\n"
                + "        fontFamily: \"arial\",\n"
                + "        fontWeight: \"bolder\",\n"
                + "        zIndex: \"1\",\n"
                + "        textShadow: \"0px 0px 5px #fff\",\n"
                + "\n"
                + "    };\n"
                + "    const loginLink = {\n"
                + "        color: \"#000\",\n"
                + "        textDecoration: \"none\",\n"
                + "        fontWeight: \"bolder\",\n"
                + "        fontFamily: \"arial black\",\n"
                + "        fontSize: \"13px\"\n"
                + "\n"
                + "    };\n"
                + "    const iconStyle = {\n"
                + "        color: \"#2ccdf5\",\n"
                + "        marginRight: \"5px\"\n"
                + "\n"
                + "    };\n"
                + "    const brandStyles={\n"
                + "        color: \"#fff\",\n"
                + "        textDecoration: \"none\",\n"
                + "        fontWeight: \"bolder\",\n"
                + "        fontFamily: \"arial black\",\n"
                + "        fontSize: \"20px\",textShadow: \"0px 0px 5px #000\"\n"
                + "    }\n"
                + "    const subMenuTitle={\n"
                + "        name: \"<span style={{color:'#000'}}>Action</span>\"\n"
                + "    }\n"
                + "    return (\n"
                + "    \n"
                + "\n"
                + "\n"
                + "        <Navbar sticky=\"top\" collapseOnSelect expand=\"lg\" style={nav_styles} >\n"
                + "\n"
                + "            <Container>\n"
                + "                <Navbar.Brand href=\"#home\">\n"
                + "                    <img\n"
                + "                        src=\"../imgz/Logo.jpeg\"\n"
                + "                        width=\"30\"\n"
                + "                        height=\"30\"\n"
                + "                        className=\"d-inline-block align-top\"\n"
                + "                        alt=\"React Bootstrap logo\"\n"
                + "                    />\n"
                + "                </Navbar.Brand>\n"
                + "\n"
                + "\n"
                + "                <Navbar.Brand style={brandStyles} as={Link} to=\"/\">CODEGURU</Navbar.Brand>\n"
                + "                <Navbar.Toggle aria-controls=\"responsive-navbar-nav\" />\n"
                + "                <Navbar.Collapse id=\"responsive-navbar-nav\">\n"
                + "                    <Nav className=\"me-auto\">\n"
                + "                       \n"
                + ListMenus
                + "\n"
                + "                         {/* Commented to enable on demand"
                + "                             <NavDropdown style={navLinks} color='#fff'  title={ <span style={navLinks}>\n"
                + "                            \n"
                + "                            <Icon style={iconStyle}  size={22} icon={more} />\n"
                + "                            Action</span> } id=\"collasible-nav-dropdowns\">\n"
                + "                            <NavDropdown.Item as={Link} href=\"structure\"><span style={{color:'#000'}}>Sub 1</span> </NavDropdown.Item>\n"
                + "                            <NavDropdown.Item to=\"unit\">\n"
                + "                                Another action\n"
                + "                            </NavDropdown.Item>\n"
                + "                            <NavDropdown.Item as={Link} to=\"unit\">Something</NavDropdown.Item>\n"
                + "                            <NavDropdown.Divider />\n"
                + "                            <NavDropdown.Item as={Link} to=\"tuple\">\n"
                + "                                Separated link\n"
                + "                            </NavDropdown.Item>\n"
                + "                        </NavDropdown> */}"
                + "                    </Nav>\n"
                + "                    <Nav>\n"
                + "                        <Nav.Link href=\"#deets\">More deets</Nav.Link>\n"
                + "                        <Nav.Link as={Link} style={loginLink} eventKey={2} to=\"/login\">\n"
                + "                            Login\n"
                + "                        </Nav.Link>\n"
                + "                    </Nav>\n"
                + "                </Navbar.Collapse>\n"
                + "            </Container>\n"
                + "        </Navbar>\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "        // <>\n"
                + "        //     <nav style={nav_styles} className={`${my_class} navbar navbar-expand-lg  `}>\n"
                + "        //         <div className=\"d-flex flex-grow-1  \">\n"
                + "        //             <span className=\"w-100 d-lg-none d-block\">\n"
                + "        //             </span>\n"
                + "        //             <a style={my_styles} className=\"navbar-brand d-none d-lg-inline-block ps-3\" href=\"/\"> CODEGURU </a>\n"
                + "        //             <a className=\"navbar-brand-two mx-auto d-lg-none d-inline-block\" href=\"#\">\n"
                + "        //                 <img src=\"//placehold.it/40?text=LOGO\" alt=\"logo\" />\n"
                + "        //             </a>\n"
                + "        //             <div className=\"w-100 text-right\">\n"
                + "        //                 <button className=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        //                     <span className=\"navbar-toggler-icon\"></span>\n"
                + "        //                 </button>\n"
                + "        //             </div>\n"
                + "        //         </div>\n"
                + "\n"
                + "        //         <div className=\"collapse navbar-collapse flex-grow-1 text-left\">\n"
                + "        //             <ul className=\"navbar-nav ms-1 flex-nowrap\">\n"
                + "\n"
                + "        //                 <li className=\"nav-item\">\n"
                + "        //                     <Link className=\"nav-link\" style={my_styles} to={`/structure`}>\n"
                + "        //                         <Icon style={{ color: '#df7e00' }} size={24} icon={struc} />   Structure\n"
                + "        //                     </Link>\n"
                + "        //                 </li>\n"
                + "        //                 <li className=\"nav-item\">\n"
                + "        //                     <Link className=\"nav-link\" style={my_styles} to={`/unit `}>\n"
                + "        //                         <Icon style={{ color: '#df7e00'   }} size={24} icon={compass} />   Unit\n"
                + "        //                     </Link>\n"
                + "        //                 </li>\n"
                + "        //                 <li className=\"nav-item\">\n"
                + "        //                     <Link className=\"nav-link\" style={my_styles} to={`/tuple `}>\n"
                + "        //                         <Icon style={{ color: '#df7e00'  }} size={24} icon={arrival} />   Tuple\n"
                + "        //                     </Link>\n"
                + "        //                 </li>\n"
                + "\n"
                + "\n"
                + "        //             </ul>\n"
                + "        //         </div>\n"
                + "        //         <div className=\"collapse navbar-collapse flex-grow-1 text-right\" id=\"myNavbar\">\n"
                + "        //             <ul className=\"navbar-nav ms-auto flex-nowrap\">\n"
                + "\n"
                + "        //                 {(localStorage.getItem('userId') != null) ?\n"
                + "        //                     <li className=\"nav-item\">\n"
                + "        //                         <Link className=\"nav-link btn p-1  btn-light\" style={{\n"
                + "        //                             color: \"red\",\n"
                + "        //                             fontSize: \"13px\", fontWeight: \"bold\",\n"
                + "        //                             textDecoration: \"none\",\n"
                + "        //                         }} to=\"/logout\">\n"
                + "        //                             Logout\n"
                + "        //                         </Link>\n"
                + "        //                     </li>\n"
                + "        //                     :\n"
                + "        //                     <LocalLoginLink path=\"login\" />\n"
                + "        //                 }\n"
                + "\n"
                + "        //             </ul>\n"
                + "        //         </div>\n"
                + "        //     </nav>\n"
                + "\n"
                + "\n"
                + "        // </>\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export default NavbarBar\n"
                + "\n"
                + "";
    }

    public String ListMenus(String tuple) {
        return "        //                 <li className=\"nav-item\">\n"
                + "        //                     <Link className=\"nav-link\" style={my_styles} to={`/" + tuple + "`}>\n"
                + "        //                         <Icon style={{ color: '#df7e00' }} size={24} icon={struc} />   " + super.get_Capitalized(tuple) + "\n"
                + "        //                     </Link>\n"
                + "        //                 </li>\n";
    }
}
