/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src_components.navbar;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class SideBarContents extends Utils {

    public String SideBarContents() {
        return "import React, { useState } from 'react';\n"
                + "import {\n"
                + "    FaTh,\n"
                + "    FaBars,\n"
                + "    FaUserAlt,\n"
                + "    FaRegChartBar,\n"
                + "    FaCommentAlt,\n"
                + "    FaShoppingBag,\n"
                + "    FaThList\n"
                + "} from \"react-icons/fa\";\n"
                + "import { NavLink } from 'react-router-dom';\n"
                + "\n"
                + "\n"
                + "\n"
                + "const SideBar = ({ children }) => {\n"
                + "    const [isOpen, setIsOpen] = useState(false);\n"
                + "    const toggle = () => setIsOpen(!isOpen);\n"
                + "    const menuItem = [\n"
                + "        {\n"
                + "            path: \"/\",\n"
                + "            name: \"Home\",\n"
                + "            icon: <FaTh />\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/dashboard\",\n"
                + "            name: \"Dashboard\",\n"
                + "            icon: <FaTh />\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/about\",\n"
                + "            name: \"About\",\n"
                + "            icon: <FaUserAlt />\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/analytics\",\n"
                + "            name: \"Analytics\",\n"
                + "            icon: <FaRegChartBar />\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/comment\",\n"
                + "            name: \"Comment\",\n"
                + "            icon: <FaCommentAlt />\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/product\",\n"
                + "            name: \"Product\",\n"
                + "            icon: <FaShoppingBag />\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/productList\",\n"
                + "            name: \"Product List\",\n"
                + "            icon: <FaThList />\n"
                + "        }\n"
                + "    ]\n"
                + "    return (\n"
                + "        <div className=\"menuContainer\">\n"
                + "            <div style={{ width: isOpen ? \"200px\" : \"50px\" }} className=\"sidebar\">\n"
                + "                <div className=\"top_section\">\n"
                + "                    <h1 style={{ display: isOpen ? \"block\" : \"none\" }} className=\"logo\">Logo</h1>\n"
                + "                    <div style={{ marginLeft: isOpen ? \"50px\" : \"0px\" }} className=\"bars\">\n"
                + "                        <FaBars onClick={toggle} />\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "                {\n"
                + "                    menuItem.map((item, index) => (\n"
                + "                        <NavLink to={item.path} key={index} className=\"link\" activeclassName=\"active\">\n"
                + "                            <div className=\"icon\">{item.icon}</div>\n"
                + "                            <div style={{ display: isOpen ? \"block\" : \"none\" }} className=\"link_text\">{item.name}</div>\n"
                + "                        </NavLink>\n"
                + "                    ))\n"
                + "                }\n"
                + "            </div>\n"
                + "\n"
                + "            <main>{children}</main>\n"
                + "        </div>\n"
                + "\n"
                + "    );\n"
                + "};\n"
                + "\n"
                + "\n"
                + "export default SideBar\n"
                + "\n"
                + "export const DeploySubMenu = ({children}) => {\n"
                + "    const [isOpen, setIsOpen] = useState(false);\n"
                + "    const toggle = () => setIsOpen(!isOpen);\n"
                + "    const menuItem = [\n"
                + "        {\n"
                + "            path: \"/\",\n"
                + "            name: \"Home\",\n"
                + "            icon: <FaTh  size = '1em'/>\n"
                + "        } ,\n"
                + "        {\n"
                + "            path: \"/about\",\n"
                + "            name: \"About\",\n"
                + "            icon: <FaUserAlt  size = '1em'/>\n"
                + "        },\n"
                + "        {\n"
                + "            path: \"/analytics\",\n"
                + "            name: \"Analytics\",\n"
                + "            icon: <FaRegChartBar  size = '1em'/>\n"
                + "        } \n"
                + "    ]\n"
                + "\n"
                + "    const menuItemStyles={\n"
                + "        fontSize:'13px' \n"
                + "    }\n"
                + "    return (\n"
                + "        <div className=\"menuContainer \">\n"
                + "                <div style={{ width: isOpen ? \"200px\" : \"50px\" }} className=\"sidebar\">\n"
                + "                    <div className=\"top_section\">\n"
                + "                        <h1 style={{ display: isOpen ? \"block\" : \"none\" }} className=\"logo\">Logo</h1>\n"
                + "                        <div style={{ marginLeft: isOpen ? \"50px\" : \"0px\" }} className=\"bars\">\n"
                + "                            <FaBars onClick={toggle} />\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    {\n"
                + "                        menuItem.map((item, index) => (\n"
                + "                            <NavLink to={item.path} key={index} className=\"link\" activeclassName=\"active\">\n"
                + "                                <div className=\"icon\">{item.icon}</div>\n"
                + "                                <div style={{ display: isOpen ? \"block\" : \"none\", fontSize:'13px' }} className=\"link_text \">{item.name}</div>\n"
                + "                            </NavLink>\n"
                + "                        ))\n"
                + "                    }\n"
                + "                </div>\n"
                + "           \n"
                + "            <main>{children}</main>\n"
                + "        </div>\n"
                + "\n"
                + "    );\n"
                + "}";
    }
}
