/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src.navbar;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class VertNavBarContents extends Utils {

    public String VertNavBarContents() {
        return "import React from 'react'\n"
                + "import AnimateHeight from \"react-animate-height\"\n"
                + "import Icon from 'react-icons-kit'\n"
                + "import { useState } from 'react'\n"
                + "\n"
                + "import { home } from 'react-icons-kit/icomoon/home'\n"
                + "import { user } from 'react-icons-kit/icomoon/user'\n"
                + "import { userTie as admin } from 'react-icons-kit/icomoon/userTie'\n"
                + "import { man as manager } from 'react-icons-kit/icomoon/man'\n"
                + "import { users } from 'react-icons-kit/icomoon/users'\n"
                + "import { hourGlass as unfishedStructure } from 'react-icons-kit/icomoon/hourGlass'\n"
                + "import { laptop as machineLearning } from 'react-icons-kit/icomoon/laptop'\n"
                + "function VertNavBar(props) {\n"
                + "\n"
                + "    const [menuheight, setMenuHeight] = useState(0);\n"
                + "    return (\n"
                + "        <div>\n"
                + "            <div className=\"container-fluid navContainer\"  >\n"
                + "                <div className=\"row \">\n"
                + "                    <div className=\"  col-md-2 col-xl-2 px-sm-2 px-0  verNavBar\"     >\n"
                + "                        <div className=\"d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-99\">\n"
                + "                            <a href=\"#\" className=\"d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none\">\n"
                + "                                <span className=\"fs-5 d-none d-sm-inline\">Menu</span>\n"
                + "                            </a>\n"
                + "                            <ul className=\"nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start\" id=\"menu\">\n"
                + "                                <li className=\"nav-item\">\n"
                + "                                    <a href=\"#\" className=\"nav-link align-middle px-0\">\n"
                + "                                        <Icon icon={home} />   <span className=\"ms-1 d-none d-sm-inline\">Home</span>\n"
                + "                                    </a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"#\" data-bs-toggle=\"collapse\" className=\"nav-link px-0 align-middle\"\n"
                + "                                        aria-expanded={menuheight !== 0} aria-controls=\"aniMenu1\" onClick={() => setMenuHeight(menuheight === 0 ? 'auto' : 0)} >\n"
                + "                                        <Icon style={{ color: '#fff' }} icon={user} />\n"
                + "                                        <span className=\"ms-1 d-none d-sm-inline\"\n"
                + "                                            aria-expanded={menuheight !== 0} aria-controls=\"aniMenu1\" onClick={() => setMenuHeight(menuheight === 0 ? 'auto' : 0)}\n"
                + "                                        >Dashboard</span>\n"
                + "                                    </a>\n"
                + "                                    <AnimateHeight\n"
                + "                                        id=\"aniMenu1\"\n"
                + "                                        duration={300} animateOpacity={true}\n"
                + "                                        menuheight={menuheight}>\n"
                + "                                        <ul className=\"collapse show nav flex-column ms-1\" id=\"submenu1\" data-bs-parent=\"#menu\">\n"
                + "                                            <li className=\"w-100\">\n"
                + "                                                <a href=\"#\" className=\"nav-link px-0\">\n"
                + "                                                    <Icon icon={admin} style={{marginRight: \"8px\"}} />\n"
                + "                                                    <span className=\"d-none d-sm-inline\">Administrator </span>  </a>\n"
                + "                                            </li>\n"
                + "                                            <li>\n"
                + "                                                <a href=\"#\" className=\"nav-link px-0\"> <Icon icon={manager} /> <span className=\"d-none d-sm-inline\">Manager</span>  </a>\n"
                + "                                            </li>\n"
                + "                                        </ul>\n"
                + "                                    </AnimateHeight>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"#\" className=\"nav-link px-0 align-middle\">\n"
                + "                                        <Icon icon={users} /> <span className=\"ms-1 d-none d-sm-inline\">Users</span></a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"#\" data-bs-toggle=\"collapse\" className=\"nav-link px-0 align-middle \">\n"
                + "                                        <Icon icon={unfishedStructure} /><span className=\"ms-1 d-none d-sm-inline\">Unfinished Structures</span></a>\n"
                + "                                    <ul className=\"collapse nav flex-column ms-1\" id=\"submenu2\" data-bs-parent=\"#menu\">\n"
                + "                                        <li className=\"w-100\">\n"
                + "                                            <a href=\"#\" className=\"nav-link px-0\"> <span className=\"d-none d-sm-inline\">Delayed</span> 1</a>\n"
                + "                                        </li>\n"
                + "                                        <li>\n"
                + "                                            <a href=\"#\" className=\"nav-link px-0\"> <span className=\"d-none d-sm-inline\">Costly Structures</span> 2</a>\n"
                + "                                        </li>\n"
                + "                                    </ul>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"#\" data-bs-toggle=\"collapse\" className=\"nav-link px-0 align-middle\">\n"
                + "                                        <Icon icon={machineLearning} /> <span className=\"ms-1 d-none d-sm-inline\">Machine Learning </span> </a>\n"
                + "                                    <ul className=\"collapse nav flex-column ms-1\" id=\"submenu3\" data-bs-parent=\"#menu\">\n"
                + "                                        <li className=\"w-100\">\n"
                + "                                            <a href=\"#\" className=\"nav-link px-0\"> <span className=\"d-sm-inline\">JAVA </span> 1</a>\n"
                + "                                        </li>\n"
                + "                                        <li>\n"
                + "                                            <a href=\"#\" className=\"nav-link px-0\"> <span className=\"d-sm-inline\">PYTHON</span> 2</a>\n"
                + "                                        </li>\n"
                + "                                        <li>\n"
                + "                                            <a href=\"#\" className=\"nav-link px-0\"> <span className=\"d-sm-inline\">PHP</span> 3</a>\n"
                + "                                        </li>\n"
                + "                                    </ul>\n"
                + "                                </li>\n"
                + "                            </ul>\n"
                + "                            <hr />\n"
                + "                            <div className=\"dropdown pb-4\">\n"
                + "                                <a href=\"#\" className=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle\" id=\"dropdownUser1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n"
                + "                                    <img src=\"https://github.com/mdo.png\" alt=\"hugenerd\" width=\"30\" height=\"30\" className=\"rounded-circle\" />\n"
                + "                                    <span className=\"d-none d-sm-inline mx-1\">SANGWA</span>\n"
                + "                                </a>\n"
                + "                                <ul className=\"dropdown-menu dropdown-menu-dark text-small shadow\">\n"
                + "                                    <li><a className=\"dropdown-item\" href=\"#\">New project...</a></li>\n"
                + "                                    <li><a className=\"dropdown-item\" href=\"#\">Settings</a></li>\n"
                + "                                    <li><a className=\"dropdown-item\" href=\"#\">Profile</a></li>\n"
                + "                                    <li>\n"
                + "                                        <hr className=\"dropdown-divider\" />\n"
                + "                                    </li>\n"
                + "                                    <li><a className=\"dropdown-item\" href=\"#\">Sign out</a></li>\n"
                + "                                </ul>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <div className=\"col-md-10 pt-3 border border-dark\">\n"
                + "                        {props.children}\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "            </div >\n"
                + "\n"
                + "\n"
                + "        </div >\n"
                + "    )\n"
                + "}\n"
                + "\n"
                + "export default VertNavBar";
    }
}
