/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.codeguru_base.codes.frontendreact.src.home;

import com.codeguru_base.util.Utils;

/**
 *
 * @author SANGWA Emmanuel code [CODEGURU - info@codeguru.com]
 */
public class Home_BannerContents extends Utils {

    public String AppCss(String welcomeMsg1, String welcomeMsg2, String welcomeMsg3, String welcomeMsg4,String welcomeMsg5,String welcomeMsg6){
        return "import React, { useEffect, useState } from 'react'\n"
                + "import { Slide } from 'react-slideshow-image';\n"
                + "import 'react-slideshow-image/dist/styles.css'\n"
                + "\n"
                + "import $ from \"jquery\"\n"
                + "import \"jquery-ui-pack/jquery-ui\"\n"
                + "\n"
                + "function Banner() {\n"
                + "    const [alerted, setAlerted] = useState(\"Done \")\n"
                + "    const [countResetabble, setCountResetabble] = useState(0)\n"
                + "    const [counter, setCounter] = useState(0);\n"
                + "    const [txtDisplay, setTxtDisplay] = useState(\"Technology & design studio\")\n"
                + "\n"
                + "    var time_taken = 3100;\n"
                + "    var each_after = 5000;\n"
                + "\n"
                + "    //start anim status\n"
                + "    const swin = window.innerWidth\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "    // $('#item').html('counted..: ' + counter)\n"
                + "\n"
                + "\n"
                + "    // $('#item').animate({ left: width_to_slide }, time_taken, 'easeInQuad');\n"
                + "\n"
                + "\n"
                + "    const txtChanger = () => {\n"
                + "        if (countResetabble == 1) {\n"
                + "            setTxtDisplay(\""+welcomeMsg1+"\")\n"
                + "        } else if (countResetabble == 2) {\n"
                + "            setTxtDisplay(\""+welcomeMsg2+"\")\n"
                + "        } else if (countResetabble == 3) {\n"
                + "            setTxtDisplay(\""+welcomeMsg3+"\")\n"
                + "        } else if (countResetabble == 4) {\n"
                + "            setTxtDisplay(\""+welcomeMsg4+"\")\n"
                + "\n"
                + "        } else if (countResetabble == 5) {\n"
                + "            setTxtDisplay(\""+welcomeMsg5+"\")\n"
                + "        } else if (countResetabble == 6) {\n"
                + "            setTxtDisplay(\""+welcomeMsg6+"\")\n"
                + "        }\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "    useEffect(() => {\n"
                + "        const interval = setInterval(() => {\n"
                + "            setCounter((prevCounter) => prevCounter + 1);\n"
                + "            txtChanger()\n"
                + "            if (counter % 8 == 0) {\n"
                + "                setCountResetabble((c) => c + 1)\n"
                + "                const slideWidth = $('#item').width()\n"
                + "\n"
                + "                const leftPos = swin - slideWidth / 2\n"
                + "                const width_to_slide = swin - slideWidth;\n"
                + "                setAlerted(\" reached 5\")\n"
                + "                $('#item').css('left', -swin)\n"
                + "                $('#item').animate({ left: width_to_slide }, time_taken, 'easeInOutQuint');\n"
                + "\n"
                + "\n"
                + "            }\n"
                + "            if (countResetabble == 7) {\n"
                + "                setCountResetabble(0)\n"
                + "            }\n"
                + "\n"
                + "\n"
                + "        }, 1000);\n"
                + "\n"
                + "\n"
                + "        // $('#item').animate({left: width_to_slide}, time_taken, 'easeInQuad');\n"
                + "\n"
                + "        return () => clearInterval(interval);\n"
                + "    }, [counter]);\n"
                + "\n"
                + "\n"
                + "\n"
                + "    return (\n"
                + "        <div className=\" gBanner border border-dark \">\n"
                + "            {/* <div id='slide1'\n"
                + "                style={{ width: \"100px\", \n"
                + "                height: \"50px\", \n"
                + "                backgroundColor: \"#000\",\n"
                + "\n"
                + "                 color: \"#fff\" }} className='abs'>Animated</div> */}\n"
                + "\n"
                + "            <div className='overlay'>\n"
                + "\n"
                + "            </div>\n"
                + "            <h1 id=\"item\"\n"
                + "                style={{ left: -swin }}\n"
                + "                className='bannerTitle  lg_txt_45 md_txt_30 sm_txt_24   sm_mt_100'> {txtDisplay}  </h1>\n"
                + "            <p>\n"
                + "                <button className='btn  bannerMore'>More...</button>\n"
                + "            </p>\n"
                + "        </div>\n"
                + "\n"
                + "    )\n"
                + "\n"
                + " \n"
                + "\n"
                + "\n"
                + "}\n"
                + "\n"
                + "export default Banner";
    }
}
